name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama desde la que quieres desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualiza a la versión v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Asegúrate de usar la versión v3
        with:
          node-version: '20'  # Puedes cambiar a '20' si prefieres Node.js 20

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Actualiza a la versión v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          force_orphan: true  # Esto elimina la historia anterior de la rama gh-pages y evita problemas con los commits
